language: python
python:
  - "3.4"
  - "3.5"
# command to install dependencies
install:
  - pip install .
  - pip install -r requirements.txt
  - pip install coveralls
# command to run tests
script: --cov-report= --cov=eva_cttv_pipeline tests/
after_success:
  coveralls