language: python
python:
  - "3.4"
  - "3.5"
# command to install dependencies
install:
  - pip install .
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install python-coveralls
# command to run tests
script:
  - bash run_tests.sh
after_success:
  - coveralls
