language: python
python:
  - "3.4"
  - "3.5"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - python setup.py install
# command to run tests
script:
  - coverage run --source=eva_cttv_pipeline setup.py test
after_success:
  - coveralls
